//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3CXInfo
{


    public partial class CallerInfo
    {

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new _3CXInfo.Site1 Master
        {
            get
            {
                return ((_3CXInfo.Site1)(base.Master));
            }
        }
    }
}
